Web1/Controllers/CourseController.cs
using LinqToDB.Data;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web1.Models;

namespace Web1.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course

        private void PrepareViewBag()
        {
            using (var CCCT = new EF.TrainingContext())
            {
                ViewBag.Cate = CCCT.category.Select(b => new SelectListItem
                {
                    Text = b.Name,
                    Value = b.id.ToString()
                }).ToList();

                //ViewBag.category = CCCT.category.ToList();
            }
        }


        //public ActionResult CourseView(int id)
        //{
        //    using(var CCCT =new EF.TrainingContext())
        //    {
        //        var course = CCCT.course.FirstOrDefault(c => c.id == id)

        //        return View(course);
        //    }
        //}

        
        private void ViewInfo(int id)
        {
            var l = new List<Trainee>();
            using (var CCCT = new EF.TrainingContext())
            {
                var t = CCCT.trainee.OrderBy(c => c.id).ToList();
                
            }
        }

        [HttpGet]
        public ActionResult CourseAdd()
        {
            PrepareViewBag();
            return View();
        }
        [HttpPost]
        public ActionResult CourseAdd(Course course)
        {
            //customvalidation(course);
            if (!ModelState.IsValid)
            {
                PrepareViewBag();
                return View(course);
            }
            else
            {
                using(var CCCT = new EF.TrainingContext())
                {
                    CCCT.course.Add(course);
                    CCCT.SaveChanges();
                }
                TempData["message"] = $"Add successfully a course with id: {course.id}";
                return RedirectToAction("CourseView");
            }
        }
        
        [HttpGet]
        public ActionResult CourseEdit(int id)
        {
            using(var CCCT = new EF.TrainingContext())
            {
                var course = CCCT.course.FirstOrDefault(c => c.id == id);
                if (course != null)
                {
                    PrepareViewBag();
                    return View(course);
                }
                else
                {
                    return RedirectToAction("CourseView");
                }
            }
        }
        [HttpPost]
        public ActionResult CourseEdit(int id, Course c)
        {
            //customvalidation(c);
            if (!ModelState.IsValid)
            {
                PrepareViewBag();
                return View(c);
            }
            else
            {
                using(var CCCT= new EF.TrainingContext())
                {
                    CCCT.Entry<Course>(c).State = System.Data.Entity.EntityState.Modified;
                    CCCT.SaveChanges();
                }
                TempData["message"] = $"Edit successfully a course with id: {c.id}";
                return RedirectToAction("CourseView");
            }
        }

        public ActionResult CourseDelete(int id)
        {
            using(var CCCT = new EF.TrainingContext())
            {
                var c = CCCT.course.FirstOrDefault(b => b.id == id);
                if (c != null)
                {
                    CCCT.course.Remove(c);
                    CCCT.SaveChanges();
                }
                TempData["message"] = $"Delete successfully a course with id: {c.id}";
                return RedirectToAction("CourseView");
            }
        }

        //private void customvalidation(Course course)
        //{
        //    DateTime time1 = course.Date;
        //    DateTime time2 = new DateTime(2000, 01, 01);

        //    string mon = Convert.ToString(course.Date.Month);
        //    string da = Convert.ToString(course.Date.Year);
        //    string na = Convert.ToString(course.Name);

        //    if (!string.IsNullOrEmpty(na) && !string.IsNullOrEmpty(da) && na.Length < 6)
        //    {
        //        ModelState.AddModelError("Name", "Name must be 6 or more than characters!!!");
        //    }
        //    else if (!string.IsNullOrEmpty(na) && na[0] != 'C')
        //    {
        //        ModelState.AddModelError("Name", "Name have to start with letter C!!!");
        //    }


        //    else if (!string.IsNullOrEmpty(na) && na[5] != 'G' && !string.IsNullOrEmpty(na) && na[5] != 'I' && !string.IsNullOrEmpty(na) && na[5] != 'L')
        //    {
        //        ModelState.AddModelError("Name", "The sixth character must be G, I or L!!!");
        //    }

        //    else if (time2 > time1)
        //    {
        //        ModelState.AddModelError("Date", "Date must after 2001/01/01!!!");
        //    }


        //    else if (course.Date.Month < 10)
        //    {
        //        if (!string.IsNullOrEmpty(na) && na[3] != '0' || !string.IsNullOrEmpty(na) && na[4] != mon[0])
        //        {

        //            ModelState.AddModelError("Name", "The fourth and fifth characters must be month!!!");
        //        }

        //        else if (!string.IsNullOrEmpty(na) && na[1] != da[2] || !string.IsNullOrEmpty(na) && na[2] != da[3])
        //        {
        //            ModelState.AddModelError("name", "second and third characters must be year of start date!");
        //        }

        //    }
        //    else if (course.Date.Month >= 10)
        //    {
        //        if (!string.IsNullOrEmpty(na) && na[3] != mon[0] || !string.IsNullOrEmpty(na) && na[4] != mon[1])
        //        {
        //            ModelState.AddModelError("Name", "The fourth and fifth characters must be month!!!");
        //        }

        //        else if (!string.IsNullOrEmpty(na) && na[1] != da[2] || !string.IsNullOrEmpty(na) && na[2] != da[3])
        //        {
        //            ModelState.AddModelError("name", "second and third characters must be year of start date!");
        //        }

        //    }


        //}
    }
}

Web1/Controllers/TraineeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web1.Models;
using System.Data.Entity;

namespace Web1.Controllers
{
    public class TraineeController : Controller
    {
        // GET: Trainee
        private void prepare()
        {
            using(var CCCT = new EF.TrainingContext())
            {
                ViewBag.Course = CCCT.course.ToList();
            }
        }

        private List<Course> LoadCourse(EF.TrainingContext CCCT, string form)
        {
            if (form != null)
            {
                var selected = form.Split(',').Select(id => Int32.Parse(id)).ToArray();
                return CCCT.course.Where(c => selected.Contains(c.id)).ToList();
            }
            else
            {
                return CCCT.course.Where(c => c.id == 0).ToList();
            }
        }

        public ActionResult TraineeView()
        {
            using(var CCCT = new EF.TrainingContext())
            {
                var trainee = CCCT.trainee.OrderBy(c => c.id).ToList();
                return View(trainee);
            }
        }

        [HttpGet]
        public ActionResult TraineeAdd()
        {
            prepare();
            return View();
        }

        [HttpPost]
        public ActionResult TraineeAdd(Trainee t, FormCollection f)
        {
            //customvalidation(t);
            if (!ModelState.IsValid)
            {
                prepare();
                TempData["courseIds"] = f["courseIds[]"];
                return View(t);
            }
            else
            {
                using(var CCCT = new EF.TrainingContext())
                {
                    t.courses = LoadCourse(CCCT, f["courses[]"]);
                    CCCT.trainee.Add(t);
                    CCCT.SaveChanges();
                }
                TempData["message"] = $"Add successfully a trainee with id: {t.id}";
                return RedirectToAction("TraineeView");
            }
        }


        [HttpGet]
        public ActionResult TraineeEdit(int id)
        {
            using(var CCCT = new EF.TrainingContext())
            {
                var trainee = CCCT.trainee.Include(c=>c.courses)
                    .FirstOrDefault(t => t.id == id);
                if(trainee != null)
                {
                    prepare();
                    return View(trainee);
                }
                else
                {
                    return RedirectToAction("TraineeView");
                }
            }
        }

        [HttpPost]
        public ActionResult TraineeEdit(int id, Trainee t, FormCollection f)
        {
            //customvalidation(t);
            if (!ModelState.IsValid)
            {
                prepare();
                TempData["courseIds"] = f["courseIds[]"];
                return View(t);
            }
            else
            {
                using(var CCCT = new EF.TrainingContext())
                {
                    CCCT.Entry<Trainee>(t).State = System.Data.Entity.EntityState.Modified;
                    CCCT.Entry<Trainee>(t).Collection(c => c.courses).Load();
                    t.courses = LoadCourse(CCCT, f["courseIds[]"]);
                    CCCT.SaveChanges();
                }
                TempData["message"] = $"Edit successfully a trainee with id: {t.id}";
                return RedirectToAction("TraineeView");
            }
        }

        public ActionResult TraineeDelete(int id)
        {
            using(var CCCT = new EF.TrainingContext())
            {
                var trainee = CCCT.trainee.FirstOrDefault(t => t.id == id);
                if(trainee != null)
                {
                    CCCT.trainee.Remove(trainee);
                    CCCT.SaveChanges();
                }

                TempData["message"] = $"Delete successfully a trainee with id: {trainee.id}";
                return RedirectToAction("TraineeView");
            }
        }

        //private void customvalidation(Trainee t)
        //{

        //    string co = Convert.ToString(t.Contact);

        //    if (!string.IsNullOrEmpty(co) && co[0] != '0')
        //    {
        //        ModelState.AddModelError("Name", "Contact have to start with number 0!!!");
        //    }

        //}
    }
}

Web1/Controllers/TrainerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web1.Models;
using System.Data.Entity;

namespace Web1.Controllers
{
    public class TrainerController : Controller
    {
        // GET: Trainer
        private void Prepare()
        {
            using(var CCCT = new EF.TrainingContext())
            {
                ViewBag.Course = CCCT.course.ToList();
            }
        }

        private List<Course> LoadCourse(EF.TrainingContext CCCT, string form)
        {
            if (form != null)
            {
                var selected = form.Split(',').Select(id => Int32.Parse(id)).ToArray();
                return CCCT.course.Where(c => selected.Contains(c.id)).ToList();
            }
            else
            {
                return CCCT.course.Where(c => c.id == 0).ToList();
            }
        }

        public ActionResult TrainerView()
        {
            using(var CCCT = new EF.TrainingContext())
            {
                var trainer = CCCT.trainer.OrderBy(c => c.id).ToList();
                return View(trainer);
            }
        }

        [HttpGet]
        public ActionResult TrainerAdd()
        {
            Prepare();
            return View();
        }

        [HttpPost]
        public ActionResult TrainerAdd(Trainer t, FormCollection f)
        {
            //customvalidation(t);
            if (!ModelState.IsValid)
            {
                Prepare();
                TempData["courseIds"] = f["courseIds[]"];
                return View(t);
            }
            else
            {
                using(var CCCT = new EF.TrainingContext())
                {
                    t.courses = LoadCourse(CCCT, f["courses[]"]);
                    CCCT.trainer.Add(t);
                    CCCT.SaveChanges();
                }
                TempData["message"] = $"Add successfully a trainer with id: {t.id}";
                return RedirectToAction("TrainerView");
            }
        }
        [HttpGet]
        public ActionResult TrainerEdit(int id)
        {
            using(var CCCT = new EF.TrainingContext())
            {
                var trainer = CCCT.trainer.Include(c=>c.courses)
                                    .FirstOrDefault(b => b.id == id);
                if(trainer != null)
                {
                    Prepare();
                    return View(trainer);
                }
                else
                {
                    return RedirectToAction("TrainerView");
                }
            }
        }

        [HttpPost]
        public ActionResult TrainerEdit(int id, Trainer t, FormCollection f)
        {
            //customvalidation(t);
            if (!ModelState.IsValid)
            {
                Prepare();
                TempData["courseIds"] = f["courseIds[]"];
                return View(t);
            }
            else
            {
                using(var CCCT =new EF.TrainingContext())
                {
                    CCCT.Entry<Trainer>(t).State = System.Data.Entity.EntityState.Modified;
                    CCCT.Entry<Trainer>(t).Collection(c => c.courses).Load();
                    t.courses = LoadCourse(CCCT, f["courseIds[]"]);
                    CCCT.SaveChanges();
                }
                TempData["message"] = $"Edit successfully a trainer with id: {t.id}";
                return RedirectToAction("TrainerView");
            }
        }

        public ActionResult TrainerDelete(int id)
        {
            using(var CCCT = new EF.TrainingContext())
            {
                var trainer = CCCT.trainer.FirstOrDefault(c => c.id == id);
                if(trainer != null)
                {
                    CCCT.trainer.Remove(trainer);
                    CCCT.SaveChanges();
                }
                TempData["message"] = $"Delete successfull a trainer with id: {trainer.id}";
            }
            return RedirectToAction("TrainerView");
        }
        //private void customvalidation(Trainer trainer)
        //{
        //    string mon = Convert.ToString(trainer.DOB.Month);
        //    string ye = Convert.ToString(trainer.DOB.Year);
        //    string ss = Convert.ToString(trainer.SSID);


        //    if (!string.IsNullOrEmpty(ss) && ss.Length < 11)
        //    {
        //        ModelState.AddModelError("Name", "SSID must be more characters!!!");
        //    }
        //    else if (!string.IsNullOrEmpty(ye) && ye.Length < 4)
        //    {
        //        ModelState.AddModelError("Name", "Date is invalid!!!");
        //    }
        //    else if (!string.IsNullOrEmpty(ss) && ss[0] != '0' && !string.IsNullOrEmpty(ss) && ss[0] != '1')
        //    {
        //        ModelState.AddModelError("Name", "SSID have to start with number 0 or 1!!!");
        //    }
        //    else if (!string.IsNullOrEmpty(ss) && ss[1] != '0' && !string.IsNullOrEmpty(ss) && ss[1] != '1')
        //    {
        //        ModelState.AddModelError("Name", "SSID have second number is 0 or 1!!!");
        //    }

        //    else if (!string.IsNullOrEmpty(ye) && ss[2] != ye[2] || !string.IsNullOrEmpty(ye) && ss[3] != ye[3])
        //    {
        //        ModelState.AddModelError("Name", "The third and fourth number of SSID are year of DOB!!!");
        //    }

        //    else if (trainer.DOB.Month < 10)
        //    {
        //        if (!string.IsNullOrEmpty(ss) && ss[4] != '0' || !string.IsNullOrEmpty(ss) && ss[5] != mon[0])
        //        {

        //            ModelState.AddModelError("Name", "The fifth and sixth numbers must be month!!!");
        //        }

        //    }
        //    else if (trainer.DOB.Month >= 10)
        //    {
        //        if (!string.IsNullOrEmpty(ss) && ss[4] != mon[0] || !string.IsNullOrEmpty(ss) && ss[5] != mon[1])
        //        {
        //            ModelState.AddModelError("Name", "The fifth and sixth numbers must be month!!!");
        //        }

        //    }
        //}
    }
}

Web1/Views/Trainer/TrainerAdd.cshtml
@model Web1.Models.Trainer
@{
    ViewBag.Title = "TrainerAdd";
    Layout = "~/Views/Shared/FormHome.cshtml";
}

@{
    List<int> selectedids = new List<int>();
    if(TempData["courseIds"] != null)
    {
        selectedids = TempData["courseIds"].ToString().Split(',')
        .Select(id => Int32.Parse(id)).ToList();
    }
}

<div class="container">
    <h1 class="display-4">New Trainer</h1>
    @if (!ViewData.ModelState.IsValid)
    {
        @Html.ValidationSummary(false,"Error", new {@class = "text-danger"})
    }

    @using (Html.BeginForm(FormMethod.Post))
    {
        @Html.Partial("_Formcreate1")

        ////course
        <div class="form-group">
            <label class="font-weight-bold mr-3">
                Courses
            </label>
            <br />
            @foreach (var r in ViewBag.Course)
            {
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox"
                           value="@r.id" id="@r.Name" name="courseIds[]"
                           @(selectedids.Contains(r.id) ? "checked" : string.Empty) />
                    <label class="form-check-label" for="@r.Name">
                        @r.Name
                    </label>
                </div>
            }
        </div>

        <button type="submit" class="btn btn-dark">Submit</button>
    }
</div>

Web1/Views/Trainer/TrainerEdit.cshtml
@model Web1.Models.Trainer
@{
    ViewBag.Title = "TrainerEdit";
    Layout = "~/Views/Shared/FormHome.cshtml";
}

@{
    List<int> selectedids = new List<int>();
    if (TempData["courseIds"] != null)
    {
        selectedids = TempData["courseIds"].ToString().Split(',')
        .Select(id => Int32.Parse(id)).ToList();
    }
    else if(Model != null)
    {
        selectedids = Model.courses.Select(r => r.id).ToList();
    }
}

<div class="container">
    <h1 class="display-4">Edit Trainer</h1>
    @if (!ViewData.ModelState.IsValid)
    {
        @Html.ValidationSummary(false, "Error", new { @class = "text-danger" })
    }

    @using (Html.BeginForm(FormMethod.Post))
    {
        @Html.Partial("_Formcreate1")

        <div class="form-group">
                <label class="font-weight-bold mr-3">
                    Courses
                </label>
                <br />
                @foreach (var c in ViewBag.Course)
                {
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox"
                               value="@c.id" id="@c.Name" name="courseIds[]"
                               @(selectedids.Contains(c.id) ? "checked" : string.Empty) />
                        <label class="form-check-label" for="@c.Name">
                            @c.Name
                        </label>
                    </div>
                }
            </div>

        <button type="submit" class="btn btn-dark">Submit</button>
    }
</div>

Web1/Views/Trainer/TrainerView.cshtml
@model IEnumerable<Web1.Models.Trainer>
@{
    ViewBag.Title = "TrainerView";
    Layout = "~/Views/Shared/FormHome.cshtml";
}

<br />
<h1 align="center">Trainer Manager</h1>

<div class="style">
    @if (TempData["message"] != null)
    {
        ViewBag.Message = TempData["message"];
    }
    @Html.Partial("_Message")
</div>


<table class="style" border="1">
   
    <tr>
        <td class="td"><b>@Html.DisplayNameFor(model => model.Name)</b></td>
        <td class="td"><b>@Html.DisplayNameFor(model => model.Workplace)</b></td>
        <td class="td"><b>@Html.DisplayNameFor(model => model.Email)</b></td>
        <td class="td"><b>@Html.DisplayNameFor(model => model.Phonenumber)</b></td>
        <td class="td"></td>
        <td class="td"></td>
    </tr>
    @foreach (var b in Model)
    {
<tr>
    <td class="td">@Html.DisplayFor(model => b.Name)</td>
    <td class="td">@Html.DisplayFor(model => b.Workplace)</td>
    <td class="td">@Html.DisplayFor(model => b.Email)</td>
    <td class="td">@Html.DisplayFor(model => b.Phonenumber)</td>
    <td class="td">
        <a type="button" class="btn btn-outline-info"
           href="@Url.Action("ViewCourse",new { id = b.id})">View</a>
    </td>

    <td class="td">
        <a type="button" class="btn btn-success"
           href="@Url.Action("TrainerEdit",new {id =b.id})">Edit</a>
    </td>
    <td class="td">
        <a type="button" class="btn btn-danger"
           data-trainer="@String.Format("{0}|{1}",
                                             b.ToSeparatedString("|"),
                                             Url.Action("CourseDelete",new { id = b.id}))"
           data-target="#delete" data-toggle="modal">Delete</a>
    </td>
</tr>

    }
</table>

@section alertdialog
    {
    <div class="modal fade" tabindex="-1" id="delete" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">


                <form id="deleteForm" method="post">
                    <div class="modal-header">
                        <h5 class="modal-title">Deleting A Trainer</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <table class="maxwith">
                            <tr style="height: 40px">
                                <th scope="col" width="20%">Name</th>
                            </tr>
                            <tr>
                                <th><input type="text" class="form-control" id="name" /></th>
                            </tr>
                            <tr style="height: 40px">
                                <th scope="col" width="20%">Type</th>
                            </tr>
                            <tr>
                                <th><input type="text" class="form-control" id="type" /></th>
                            </tr>
                            <tr style="height: 40px">
                                <th scope="col" width="20%">Work Place</th>
                            </tr>
                            <tr>
                                <th><input type="text" class="form-control" id="workplace" /></th>
                            </tr>
                            <tr style="height: 40px">
                                <th scope="col" width="20%">Phone Number</th>
                            </tr>
                            <tr>
                                <th><input type="text" class="form-control" id="phonenumber" /></th>
                            </tr>
                            <tr style="height: 40px">
                                <th scope="col" width="20%">Email</th>
                            </tr>
                            <tr>
                                <th><input type="text" class="form-control" id="email" /></th>
                            </tr>

                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <input type="submit" class="btn btn-primary" value="Delete" />
                    </div>

                </form>
            </div>
        </div>
    </div>
}

@section scripts
    {
    <script type="text/javascript">
        $('document').ready(function () {
            $('a[data-trainer]').on('click', function (evt) {
                let d = $(this).attr('data-trainer').split("|");
                console.log(d);
                $('#id').attr('value', d[0]);
                $('#name').attr('value', d[1]);
                $('#type').attr('value', d[2]);
                $('#workplace').attr('value', d[3]);
                $('#phonenumber').attr('value', d[4]);
                $('#email').attr('value', d[5]);

                $('#deleteForm').attr('action', d[4]);
            });
        });

    </script>
}

Web1/Views/Trainer/_Formcreate1.cshtml
@model Web1.Models.Trainer

@*<div class="form-group">
    @Html.LabelFor(m => m.categoryid, htmlAttributes: new { @class = "font-weight-bold" })
    @Html.DropDownListFor(m => m.categoryid, (IEnumerable<SelectListItem>)ViewBag.Cate,
    htmlAttributes: new { @class = "form-control" })
</div>*@

<div class="form-group">
    @Html.LabelFor(m => m.Name,
    htmlAttributes: new { @class = "font-weight-bold" })
    @Html.EditorFor(m => m.Name,
       new
            {
       htmlAttributes = new { @class = "form-control" }
       })
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Type,
    htmlAttributes: new { @class = "font-weight-bold" })
    @Html.EditorFor(m => m.Type,
       new
            {
       htmlAttributes = new { @class = "form-control" }
       })
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Workplace,
    htmlAttributes: new { @class = "font-weight-bold" })
    @Html.EditorFor(m => m.Workplace,
       new
            {
       htmlAttributes = new { @class = "form-control" }
       })
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Phonenumber,
    htmlAttributes: new { @class = "font-weight-bold" })
    @Html.EditorFor(m => m.Phonenumber,
       new
            {
       htmlAttributes = new { @class = "form-control" }
       })
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Email,
    htmlAttributes: new { @class = "font-weight-bold" })
    @Html.EditorFor(m => m.Email,
       new
            {
       htmlAttributes = new { @class = "form-control" }
       })
</div>

Web1/Views/Trainer/_Nav1.cshtml
<nav class="navbar navbar-expand-md navbar-dark fixed-top nav-bg-color">
    <div class="container">

        <a class="navbar-brand" href="@Url.Action("", "")">
            GreenWich System
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("CourseView", "Course")">Course</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Options
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="@Url.Action("TrainerView","Trainer")">Trainer</a>
                        <a class="dropdown-item" href="@Url.Action("TraineeView", "Trainee")">trainee</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("TrainerAdd", "Trainer")">Create Trainer</a>
                    </div>
                </li>
                @*<li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Create", "ManageSchool")">More</a>
                </li>*@
            </ul>
        </div>
    </div>
</nav>